export const GEOJSON_URL = "https://ia601703.us.archive.org/6/items/prov_ma_202601/prov_ma.txt";

export const REGIONS_LIST = [
  "01. Tanger-Tétouan-Al Hoceïma",
  "02. Oriental",
  "03. Fès-Meknès",
  "04. Rabat-Salé-Kénitra",
  "05. Béni Mellal-Khénifra",
  "06. Casablanca-Settat",
  "07. Marrakech-Safi",
  "08. Drâa-Tafilalet",
  "09. Souss-Massa",
  "10. Guelmim-Oued Noun",
  "11. Laâyoune-Sakia El Hamra",
  "12. Dakhla-Oued Ed-Dahab"
];

export const ARABIC_PROVINCES: Record<string, string> = {
  "الدار البيضاء": "CASABLANCA", "الرباط": "RABAT", "مراكش": "MARRAKECH", "أكادير": "AGADIR IDA OU TANANE",
  "طنجة": "TANGER - ASILAH", "فاس": "FÈS", "مكناس": "MEKNES", "وجدة": "OUJDA - ANGAD", "تطوان": "TETOUAN",
  "القنيطرة": "KÉNITRA", "آسفي": "SAFI", "الجديدة": "EL JADIDA", "بني ملال": "BENI MELLAL", "سطات": "SETTAT",
  "الناظور": "NADOR", "تازة": "TAZA", "خريبكة": "KHOURIBGA", "تمارة": "SKHIRATE- TEMARA", "سلا": "SALÉ",
  "الخميسات": "KHEMISSET", "الرشيدية": "ERRACHIDIA", "كلميم": "GUELMIM", "تارودانت": "TAROUDANNT", 
  "الصويرة": "ESSAOUIRA", "بركان": "BERKANE", "الداخلة": "OUAD EDDAHAB", "العيون": "LAAYOUNE",
  "شفشاون": "CHEFCHAOUEN", "وزان": "OUAZZANE", "الحسيمة": "AL HOUCEIMA", "تزنيت": "TIZNIT",
  "ازيلال": "AZILAL", "خنيفرة": "KHENIFRA", "جرسيف": "GUERSSIF", "ميدلت": "MIDELT", "صفرو": "SEFROU",
  "سيدي قاسم": "SIDI KACEM", "سيدي سليمان": "SIDI SLIMANE", "برشيد": "BERCHID", "بن سليمان": "BEN SLIMANE",
  "قلعة السراغنة": "EL KELAA DES SRAGHNA", "الحوز": "AL HAOUZ", "شيشاوة": "CHICHAOUA"
};

export const PROVINCE_TO_REGION: Record<string, string> = {
  "OUAD EDDAHAB": "12. Dakhla-Oued Ed-Dahab", "AOUSSERD": "12. Dakhla-Oued Ed-Dahab",
  "LAAYOUNE": "11. Laâyoune-Sakia El Hamra", "BOUJDOUR": "11. Laâyoune-Sakia El Hamra",
  "ESSMARA": "11. Laâyoune-Sakia El Hamra", "TRAFAYA": "11. Laâyoune-Sakia El Hamra",
  "GUELMIM": "10. Guelmim-Oued Noun", "ASSA - ZAG": "10. Guelmim-Oued Noun",
  "SIDI IFNI": "10. Guelmim-Oued Noun", "TAN - TAN": "10. Guelmim-Oued Noun",
  "AGADIR IDA OU TANANE": "09. Souss-Massa", "INEZEGANE AIT MELLOUL": "09. Souss-Massa",
  "CHTOUKA AIT BAHA": "09. Souss-Massa", "TAROUDANNT": "09. Souss-Massa",
  "TIZNIT": "09. Souss-Massa", "TATA": "09. Souss-Massa",
  "TINGHIR": "08. Drâa-Tafilalet", "OURZAZTE": "08. Drâa-Tafilalet",
  "ZAGORA": "08. Drâa-Tafilalet", "MIDELT": "08. Drâa-Tafilalet",
  "ERRACHIDIA": "08. Drâa-Tafilalet", "MARRAKECH": "07. Marrakech-Safi",
  "AL HAOUZ": "07. Marrakech-Safi", "CHICHAOUA": "07. Marrakech-Safi",
  "EL KELAA DES SRAGHNA": "07. Marrakech-Safi", "REHAMNA": "07. Marrakech-Safi",
  "YOUSSOUFIA": "07. Marrakech-Safi", "SAFI": "07. Marrakech-Safi", "ESSAOUIRA": "07. Marrakech-Safi",
  "BENI MELLAL": "05. Béni Mellal-Khénifra", "AZILAL": "05. Béni Mellal-Khénifra",
  "FQUIH BEN SALAH": "05. Béni Mellal-Khénifra", "KHENIFRA": "05. Béni Mellal-Khénifra",
  "KHOURIBGA": "05. Béni Mellal-Khénifra", "CASABLANCA": "06. Casablanca-Settat",
  "MOHAMMEDIA": "06. Casablanca-Settat", "MÉDIOUNA": "06. Casablanca-Settat",
  "NOUACER": "06. Casablanca-Settat", "BERCHID": "06. Casablanca-Settat",
  "BEN SLIMANE": "06. Casablanca-Settat", "SETTAT": "06. Casablanca-Settat",
  "SIDI BENNOUR": "06. Casablanca-Settat", "EL JADIDA": "06. Casablanca-Settat",
  "RABAT": "04. Rabat-Salé-Kénitra", "SALÉ": "04. Rabat-Salé-Kénitra",
  "SKHIRATE- TEMARA": "04. Rabat-Salé-Kénitra", "KÉNITRA": "04. Rabat-Salé-Kénitra",
  "KHEMISSET": "04. Rabat-Salé-Kénitra", "SIDI KACEM": "04. Rabat-Salé-Kénitra",
  "SIDI SLIMANE": "04. Rabat-Salé-Kénitra", "FÈS": "03. Fès-Meknès",
  "MEKNES": "03. Fès-Meknès", "EL HAJEB": "03. Fès-Meknès",
  "SEFROU": "03. Fès-Meknès", "IFRANE": "03. Fès-Meknès",
  "BOULEMANE": "03. Fès-Meknès", "TAZA": "03. Fès-Meknès",
  "TAOUNATE": "03. Fès-Meknès", "MOULAY YACOUB": "03. Fès-Meknès",
  "OUJDA - ANGAD": "02. Oriental", "NADOR": "02. Oriental",
  "BERKANE": "02. Oriental", "TAOURIRT": "02. Oriental",
  "JRADA": "02. Oriental", "FIGUIG": "02. Oriental",
  "GUERSSIF": "02. Oriental", "DRIOUCH": "02. Oriental",
  "TANGER - ASILAH": "01. Tanger-Tétouan-Al Hoceïma", "M'DIQ-FNIDEQ": "01. Tanger-Tétouan-Al Hoceïma",
  "TETOUAN": "01. Tanger-Tétouan-Al Hoceïma", "LARACHE": "01. Tanger-Tétouan-Al Hoceïma",
  "AL HOUCEIMA": "01. Tanger-Tétouan-Al Hoceïma", "CHEFCHAOUEN": "01. Tanger-Tétouan-Al Hoceïma",
  "OUAZZANE": "01. Tanger-Tétouan-Al Hoceïma", "EL FAHS - ANGRA": "01. Tanger-Tétouan-Al Hoceïma"
};

export const DOWNLOAD_LINKS: Record<string, string> = {
  "AGADIR IDA OU TANANE": "https://drive.google.com/file/d/1UWDokzDiJuNO6_vqc590B87iEF9_IcTK/view",
  "AL HOUCEIMA": "https://drive.google.com/file/d/1YfXPI41zaqDRkX0LVMtdQyGlzD65ZWi-",
  "TANGER - ASILAH": "https://drive.google.com/file/d/1YlidcDUw3SPD7FeNnignFL7TesbRaxp3",
  "NADOR": "https://drive.google.com/file/d/1wanlzg6Fa9G_Wi6818LwpNn1kNTJntJm",
  "SEFROU": "https://drive.google.com/file/d/1ppx8GAqzlTGkrfG9aqX3GDkSt2m6tpJg",
  "OURZAZTE": "https://drive.google.com/file/d/1pUAIzQBujnLogFnYkx6Tyjj_bn7nS_7N",
  "KHENIFRA": "https://drive.google.com/file/d/1ROc0iqfuE_koHagIEjtORQA9jyyhrBsD",
  "MIDELT": "https://drive.google.com/file/d/1XBBoFWEYrWED6bpn0Cjv_gKOEaLqgacF",
  "LAAYOUNE": "https://drive.google.com/file/d/1skAk7DnHMT8KbdckQueH7Vt8OB1RcwUy",
  "TAZA": "https://drive.google.com/file/d/1t2o1j6mwy2BW9mkfCVzOFTS-KQhr3w4H",
  "TAOURIRT": "https://drive.google.com/file/d/14YVjpHq26bcoIjSO-VoKTVNhgzxBQdNY",
  "KHEMISSET": "https://drive.google.com/file/d/1d5IUnW_2pAhg64VUqCmf3dk8fr9fG6d_",
  "FQUIH BEN SALAH": "https://drive.google.com/file/d/1rjAx7oPAKQ00teooftXITob8yT-Qpruf",
  "BENI MELLAL": "https://drive.google.com/file/d/1anC3cMqAJrhrjhZ21NPK8CnMuJcWLHOu",
  "BERKANE": "https://drive.google.com/file/d/1sv-PSyXqi5uSg-ddUoUBJ9rh2096_OPW",
  "GUELMIM": "https://drive.google.com/file/d/1nXiPzn8Q-wXaJvoy7m7gEBZNzlY-WKc1",
  "GUERSSIF": "https://drive.google.com/file/d/1X-Z6WjtJUp7Zj-ggm9PvWJZiE_DlP0AZ",
  "MEKNES": "https://drive.google.com/file/d/1a8GSI4_0a6L1hgkaAO0LrJBZ4X0fa6K4",
  "EL HAJEB": "https://drive.google.com/file/d/1BS7zD6tcsHBTIc8_GRnPWHN06veAOavG",
  "CHTOUKA AIT BAHA": "https://drive.google.com/file/d/16H78YAucHZ2dmHBlQoEYAZjyTOeRKxrn",
  "SIDI SLIMANE": "https://drive.google.com/file/d/1Zg_ZHhCCm11UG740ntFhOojgK3Qn6ZZF",
  "ESSAOUIRA": "https://drive.google.com/file/d/1L_t0wJAVCE9ARPZqIj0oO0zs5WvGz-Tr",
  "ERRACHIDIA": "https://drive.google.com/file/d/1CQUSWjOngEjJ0wqb5KCyYZM6IwyvN5bN",
  "TIZNIT": "https://drive.google.com/file/d/1fhYvVKrfxseEfJYmFjNQIzxQaglz825M",
  "OUAD EDDAHAB": "https://drive.google.com/file/d/1W8TCjsJgGSjER0IZ8-oAd6YYIMAZzmul",
  "BERCHID": "https://drive.google.com/file/d/1urqgs3lWp_6bKJkded0vET9UI5rS2brY",
  "SKHIRATE- TEMARA": "https://drive.google.com/file/d/106K0yigp55ZDAGNQY_XVVY5WmZ-bAEJH",
  "TAROUDANNT": "https://drive.google.com/file/d/1xkm_jDhqofnXlYJwMFtXJvnotQNplNSw",
  "LARACHE": "https://drive.google.com/file/d/1BVFiiO3aRAGQRAOws-wZyeZoMBfveQS2",
  "RABAT": "https://drive.google.com/file/d/13QhQIUO1ItLQi133fQ8p2yxHsEdw0oVn",
  "INEZEGANE AIT MELLOUL": "https://drive.google.com/file/d/1yyd-GQF5BVfF4SrYlwGPEkr7ucxYhiql",
  "KHOURIBGA": "https://drive.google.com/file/d/1V-nlu6qBQIBwhCqT-yV7pHOJK_8z3AyZ",
  "FÈS": "https://drive.google.com/file/d/1a6QUwgao4okjcyR1V_Hz3BAWZVeo-MS5",
  "SIDI KACEM": "https://drive.google.com/file/d/1-exZqMZPQ62H4X3PH5iFoiic1XzSvDXv",
  "SIDI BENNOUR": "https://drive.google.com/file/d/1eLfmImakIX_B2h0KNBCYrx3LF8H0Mm--",
  "IFRANE": "https://drive.google.com/file/d/1c1w2yGvR3cahFsSbCSt7kD2maEkedhr7",
  "KÉNITRA": "https://drive.google.com/file/d/1fhdAWLXrNEcGR42QRX6b8q9zh3BfP2Ry",
  "SETTAT": "https://drive.google.com/file/d/1Rm37o7-ybmDhlLAJWg2-LUVoH0ZxqIx7",
  "TETOUAN": "https://drive.google.com/file/d/1ykxVLBOxAwNM5H61uMDdh2b05v5ftgku",
  "MOHAMMEDIA": "https://drive.google.com/file/d/1Nz8_GFQNNw_4FEgXeTHTcubYd1oxMKyt",
  "NOUACER": "https://drive.google.com/file/d/1ZTRHOun341z907E2ncXxrxjJgDd--E83",
  "CASABLANCA": "https://drive.google.com/file/d/19dK56HuNRDSxyaXPbBGA7bpaZkEo5bIq",
  "AZILAL": "https://drive.google.com/file/d/1yf752JHPOL8o8ol8bZv3_orPaqIpD60t",
  "BOULEMANE": "https://drive.google.com/file/d/1MO94Ql8RAyZaRSVW6R5uhA5wlvaA3q1L",
  "TAOUNATE": "https://drive.google.com/file/d/1nTYogtuaLXvMO6LGNkplVDIB8AGKsNrl"
};